[profile.default]
src = "src"
out = "out"
libs = ["lib"]

via_ir = true
optimizer_runs = 4294967296
solc-version = "0.8.28"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
